package harrypotter.view;

public enum View {
	STARTVIEW, CHAMPSELECTVIEW, GRYFFINDORSELECTVIEW, HUFFLEPUFFSELECTVIEW, RAVENCLAWSELECTVIEW, SLYTHERINSELECTVIEW,
	DMGSPELLVIEW, RELSPELLVIEW, HELSPELLVIEW,
	FIRSTTASKVIEW, SECONDTASKVIEW, THIRDTASKVIEW, SPELSELECTVIEW
}
